baseURL = 'https://jay.funabashi.co.uk/'
languageCode = 'en-GB'
title = 'jay.funabashi.co.uk'
theme = 'okami'
capitalizeListTitles = false

[related]
  includeNewer = true
  threshold = 70
  toLower = false
  [[related.indices]]
    name = 'date'
    weight = 80
  [[related.indices]]
    name = 'tags'
    weight = 90

[build]
  [build.buildStats]
    enable = true
  [[build.cachebusters]]
    source = 'assets/notwatching/hugo_stats\.json'
    target = 'css'
  [[build.cachebusters]]
    source = '(postcss|tailwind)\.config\.js'
    target = 'css'
[module]
  [[module.mounts]]
    source = 'assets'
    target = 'assets'
  [[module.mounts]]
    disableWatch = true
    source = 'hugo_stats.json'
    target = 'assets/notwatching/hugo_stats.json'
