# Sample workflow for building and deploying a Hugo site to GitHub Pages
name: Deploy Infrastructure

on:
  # Runs on pushes targeting the default branch
  push:
    branches: ["main"]

permissions:
  id-token: write
  contents: read

# Default to bash
defaults:
  run:
    shell: bash

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:

      - name: Install Node
        uses: actions/setup-node@v4

      - name: Install CDK
        run: |
          npm install -g aws-cdk

      - name: Checkout
        uses: actions/checkout@v4

      - uses: actions/setup-go@v5
        with:
          go-version: '>=1.17.0'

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-central-1
          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}

      - name: CDK Deploy
        working-directory: ./infra
        run: |
          cdk deploy
